# Generated by Django 5.0.3 on 2024-04-18 19:06

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 19, 6, 15, 840442, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='numericRoleLevel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_name', models.CharField(choices=[('Auditorium', 'Auditorium'), ('sem', 'Seminar hall'), ('labs', 'labs'), ('classroom', 'classroom')], max_length=20, primary_key=True, serialize=False)),
                ('resource_type', models.IntegerField(default=0)),
                ('max_permission', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)])),
                ('current_permission', models.IntegerField(default=0)),
                ('userperms', models.JSONField(blank=True, default=list, null=True)),
                ('resource_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('all_true', models.BooleanField(default=False)),
                ('curr_index', models.IntegerField(default=0)),
                ('max_index', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app1.resource')),
            ],
        ),
    ]
