# Generated by Django 4.2.3 on 2024-03-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_booking_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='neumericRoleLevel',
            new_name='numericRoleLevel',
        ),
    ]
