# Generated by Django 4.2.3 on 2024-03-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_neumericrolelevel_user_numericrolelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
