# Generated by Django 4.2.3 on 2024-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accept',
        ),
        migrations.AddField(
            model_name='booking',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='all_true',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='list',
            field=models.JSONField(default=list),
        ),
    ]
