# Generated by Django 4.1.1 on 2024-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource',
            field=models.CharField(choices=[('audi', 'Auditorium'), ('sem', 'Seminar hall')], max_length=20, unique=True),
        ),
    ]
