# Generated by Django 4.2.3 on 2024-03-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_user_accept_booking_accept_booking_all_true_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
