# Generated by Django 4.2.3 on 2024-03-14 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_booking_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_heads',
            field=models.ManyToManyField(blank=True, related_name='head_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(choices=[('audi', 'Auditorium'), ('sem', 'Seminar hall'), ('labs', 'labs'), ('classroom', 'classroom')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
