# Generated by Django 4.2.3 on 2024-03-14 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_resource_resource_heads_alter_resource_resource_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_heads',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
