# Generated by Django 4.2.3 on 2024-04-02 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_user_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 14, 19, 35, 233810, tzinfo=datetime.timezone.utc)),
        ),
    ]
